[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@nomicfoundation/=node_modules/@nomicfoundation/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "hardhat/=node_modules/hardhat/",
]

[rpc_endpoints]
arc = "${RPC_URL}"

[etherscan]
arc = { key = "placeholder", url = "https://explorer.arc.net" }